### ISSUE TITLE
[Webpack] Consider moving to `webpack-config-ca` package

### ISSUE THREAD

**Issue by avivash** [mineral-ui/mineral-ui#38]
### Description
It may be worth thinking about utilizing common CA packages, such as https://github.com/CAAPIM/webpack-config/ and https://github.com/CAAPIM/eslint-config-ca/, since they are used by other CA projects, which will be using the Mineral UI component library.

If Mineral UI is built without incorporating these packages, it likely won't function properly with other CA products when it comes time to use Mineral components.

**Comment by brentertz** [comment]
Hi Andrew,

Thank you for contributing. 

While we may gain better alignment in the future by using packages such as these, I do not believe that now is the right time to do so.  For example, we may decide to switch to rollup for our builds, instead of webpack as it is purportedly better for libraries.  Consuming applications should be agnostic of the underlying tooling.  

Further, I do not anticipate the integration problems that you suggest.  If we do run into problems, we’ll handle them when they arise.  Additionally, we’ll try to get ahead of it by doing some upfront testing, just like we did with the initial HelloWorld component.

**Comment by brentertz** [comment]
I am closing this issue as I don't believe that it necessary.  Feel free to reopen or reach out to me if you would like to discuss it further.
