### ISSUE TITLE
[Typography] Font size appears too small – sized in ems instead of rems

### ISSUE THREAD

**Issue by asagray** [mineral-ui/mineral-ui#390]
### Expected behavior

Fonts were spec'd to be sized in rems, not ems. 

### Current behavior

Ems are relative to the initial element (and are affected by cascading inheritance), while rems are relative to the root basis. Therefore, in many cases (including documentation) fonts appear smaller than intended.

### Possible solution

Find and replace `em` to `rem`. Set root basis on `html` or `body` to `16px`

**Comment by kylegach** [comment]
Hi, Aaron. Our components are designed and built to be 100% encapsulated, meaning that:

1. They don’t require _any_ styles defined outside of the component
2. They are not affected by any styles defined outside the component

We took that approach to ensure the components work consistently and as-expected in any app environment. We started styling with `rem`s, but [had to change it](https://github.com/mineral-ui/mineral-ui/issues/123) because we realized we were relying on the consuming app to use a root font-size of 16px. Since many, but not all, apps use a `html { font-size: 62.5% }` approach to effectively set the root font-size to 10px, that meant that `rem`s were out of the question, because we could not assume a common base size. Instead, we settled on using `px` at the component’s root (adjustable via a theme variable) and sizing everything inside the component in `em`s. You can see our full thoughts here:

https://docs.google.com/document/d/1dCdAJBjPLLh_9O4FlsmWrZf1zrgWA0cBEUbNnfQa2hI/edit#

The end result, both visually and capably, should be the same. If you feel that there are some font-size issues within the components themselves, please either list them here or submit new issues. Thanks.

**Comment by asagray** [comment]
Gotcha. The approach makes sense. Thanks for educating.
