### ISSUE TITLE
[Website] Add correct import syntax to Card, Menu docs

### ISSUE THREAD

**Issue by coldpour** [mineral-ui/mineral-ui#448]
We just had a customer try to import Card components like this

`import { Card, CardTitle, CustomContent } from 'mineral-ui/Card';`

I couldn't find anywhere in the docs where we explicitly call out that `Card` is the default export.

----------

As a user, I want the import syntax for components (especially when that component is a default vs. named export) documented, so that I know how to import the components I need.

#### AC
1. Import syntax added to component pages
1. User tested with 3-ish people (expert, novice)

#### Consider
* putting under "Usage" section may be too far down the page
* put under intro paragraphs at the top of the page
* make a few deploy previews and give users a task based test

**Comment by brentertz** [comment]
Just because a customer tried to do that, does not mean it is a bug.  Bugs are functional defects in code. This is not a problem with the Card component.

The proper import syntax here is below.  The primary component is the default export.  Sub components are named exports.

```js
import Card, { CardTitle, CustomContent } from 'mineral-ui/Card';
```

This is so we can have nice simple imports like the following.

```js
import Card from 'mineral-ui/Card';
```

We could add the primary component as a named export as well, but I don't believe that it is really a worthwhile pattern.

We could make this clearer by spelling it out a bit more in our [import syntax guidelines](https://github.com/mineral-ui/mineral-ui/blob/master/docs/import-syntax.md).  It also feels like we may want to turn this into a web page at some point.

**Comment by brentertz** [comment]
Here is an example of the pattern in the wild.  https://github.com/callemall/material-ui/blob/v1-beta/src/List/index.js

**Comment by brentertz** [comment]
This problem may also be exacerbated by having subcomponents at the same level as regular components in the navigation.
