### ISSUE TITLE
[Font Requirement]: A single font (Open Sans)?

### ISSUE THREAD

**Issue by loganpowell** [mineral-ui/mineral-ui#542]
I am looking at Mineral-UI as a library I might use in my next project (that should be on-going for a while), but I have requirements from our design consultants to use a specific set of fonts and colors. How badly will the UI components be broken if using other fonts?

Btw, great choice to go with Glamorous!

**Comment by trotzig** [comment]
I'm interested to hear more about this as well! I would prefer not to use a custom font on my website.

**Comment by kylegach** [comment]
Hi, Logan (and :wave: to Henric)!

Good question. I think there’s two parts to what you’re asking:

1. How do you use your own fonts and colors?
2. How does that impact the components?

For the first, we’ve built a powerful and very flexible [theming system](http://mineral-ui.com/theming/). Scroll down on that page and you can see all of the [“global” theme variables](http://mineral-ui.com/theming/#common-scenarios-theme-structure) available to you. Changing the font is as simple as setting the `fontFamily` variable in your theme. You can either set it to your own custom font (making sure you load and include the `@font-face` styles appropriately) or, if you simply wish to use system fonts, set it to `null` and the components will fall back appropriately to `fontFamily_system` (or just don't load ‘Open Sans’, and CSS will do the falling back for you).

Colors are similar, though there’s considerably more variables to consider. If you simply wish to change from blue to some other [color in the Mineral UI palette](http://mineral-ui.com/color/#guidelines-ramps), then we expose [`createTheme()`](http://mineral-ui.com/theming/#common-scenarios-api-{{44}}) to make that simple.

Also note that [each component has its own specific "theme"](http://mineral-ui.com/components/button/#theme-variables) as well. So if adjusting the “global” theme paints with too broad a brush, you can adjust things as-needed per-component.

For the second part, provided you don’t choose a relatively unique font like [Zapfino](https://en.wikipedia.org/wiki/Zapfino), the components should still look as expected. Our components are styled with a few precautions for supporting different fonts:
- For components that are likely to sit side-by-side (e.g. TextInput & Button), we set a fixed height to ensure proper alignment.
- Additionally, each component’s root element has `fontSize: theme.fontSize_base (default = 16px)` applied. Then we use `em`s for nearly all styles inside that root, so that everything will scale appropriately and consistently as the font changes. If, after applying your custom font, the components look a bit small/large, simply adjust that base value and _all_ of the components will adjust in kind.

We’re thrilled and honored you’re considering our library for your project. Please don’t hesitate to let us know if you need anything else or if anything seems unclear.

**Comment by trotzig** [comment]
As long as I can use Papyrus or Comic Sans MS, I'm happy.

**Comment by loganpowell** [comment]
@kylegach Absolutely fantastic! Thank you for the quick and detailed response. Onwards I go!
