### ISSUE TITLE
[Text] Propagate to other components

### ISSUE THREAD

**Issue by Mikewaite** [mineral-ui/mineral-ui#593]
As a developer, our components should use a comprehensive set of text-related theme variables, so that the styles are consistent and easily maintained.

AC: 
1. Identify components that use text styles
2. Update the default values of their theme variables to use the global variables
3. Update documentation as needed

**Comment by kylegach** [comment]
This story has been changed. You can see the original below.

After starting to propagate Text as originally desired, we realized two important aspects of the work:

1. For a majority of cases, the `fontFamily` & `lineHeight` styles we already get from `componentStyleReset` are the only styles we'd be using from Text.
2. For the remaining cases, which are basically headings, we expose component-level theme variables for many of the style properties provided by Text. As a result, incorporating Text actually increased lines of code and complexity, not decreased.

Because of those two factors, we decided to change the story as represented above.

*Original title:* [Text] Propagate to other components

*Original content:*
As a developer, our components that can use our newly created text component probably should be adapted to do so.

AC: 
- Identify components that could make use of our text component
- Apply the text component
- Update documentation as needed.

Other Considerations:
- Should this be a timebox issue as we have no real knowledge of which components need updating, nor priority of one component over another?
