### ISSUE TITLE
[TextInput] Styling issues

### ISSUE THREAD

**Issue by G0L0L** [mineral-ui/mineral-ui#742]
I'm trying to remove border from TextInput by using this:
`const ThemedTextInput = createThemedComponent(TextInput, {
  TextInput_borderWidth: '0px'
});`

And the code works (input element has 0 border), but in fact border remains visiblebecause of element with class `css-<some id here>-Underlay`.

As you can see on the screen it has its own styles, which remains the same.

![image](https://user-images.githubusercontent.com/1982853/43135380-7d751444-8f45-11e8-8691-bbd32c09c733.png)

**Comment by kylegach** [comment]
Thanks for the bug report, @G0L0L!

I just submitted a PR for review that will fix the issue. Should be released in the next couple days.

A couple additional notes:

- The `border: 0` on the `input` itself is always present and cannot be themed. To have the hover/focus states apply around the entire group of `startIcon`, `prefix`, `input`, `suffix`, and `endIcon`, we use that "underlay" to apply the border style (among others). Your code is correct and will work after this bug fix release; its ours that had a bug.
- If you're providing a value in `px`, you can just use a number `0` instead of including the unit in a string, `'0px'`. Either will work, though.
