### ISSUE TITLE
[Select] Unable to override Select_color

### ISSUE THREAD

**Issue by brentertz** [mineral-ui/mineral-ui#758]
### Expected behavior

Overriding `Select_color` theme variable should change the color.

### Current behavior

Overriding `Select_color` theme variable has no effect.

### Possible solution

See https://github.com/mineral-ui/mineral-ui/pull/754 for previous discussion on the matter.

### Steps to reproduce (for bugs)

There is already a test case set up for this.  See `FIXME` in `Select.spec.js`.
Simply comment out `Select_color` from the `excludedKeys` list to cause the failure.

### Version

v0.41.0

**Comment by kylegach** [comment]
After investigating, realized this is working as expected.

`Select_color` theme variable is not being overridden because the test renders a Select with no selected item. Therefore, it uses the `Select_color_placeholder` theme variable in its styles, instead of `Select_color`. `Select_color_placeholder` _is_ overridden correctly.

Removed the `FIXME` in 391e73d3a46aac4d65d6b693b16c8ccb399f85d0.

**Comment by brentertz** [comment]
Yay! \o/
