### ISSUE TITLE
[DialogBody] doesn't need to have padding top or bottom

### ISSUE THREAD

**Issue by jeeyoung** [mineral-ui/mineral-ui#769]
### Expected behavior
No padding on DialogBody

### Current behavior
padding-top:1em;
padding-top:1em;

### Possible solution
padding-top:0;
padding-top:0;

**Comment by kylegach** [comment]
Fixed with 092e0959df2b5e1a4aa3256d5f14547040505ac4.

See it live: https://mineral-ui.com/components/dialog

Thanks for catching that. FWIW, there was never padding on DialogBody. Instead, the examples were using a `<p>` for their content, which have a default top & bottom margin. We had some styles to remove the top margin from `:first-child` and the bottom margin from `:last-child`, but a refactor while building broke those styles. All fixed now and already released in v0.44.0.
