### ISSUE TITLE
Updating react-scripts and react breaks mineral-ui

### ISSUE THREAD

**Issue by oupvo01** [mineral-ui/mineral-ui#791]
### Current behavior
After updating react-scripts(2.0.5) and react(16.6.0) to the newest versions an error is thrown on page load (see picture below).
![image](https://user-images.githubusercontent.com/42371237/47721349-31744d00-dc50-11e8-8f9b-8f50e0d8106d.png)
**NOTE** We do not use propTypes ourselves.

### Expected behavior
Updating the packages mentioned above doesn't break the app and no error is thrown.

### Steps to reproduce (for bugs)
1. `npm install --save react@^16.6.0 react-dom@^16.6.0`
2.  `npm install --save --save-exact react-scripts@2.1.0`
3. `npm run build`
4. Launch a new production instance

### Context
I'd like to be able to  use the latest features of React to improve our apps performance

### Version
mineral-ui v0.44.0

**Comment by brentertz** [comment]
Hi @oupvo01 Thanks for reporting this issue.  We encountered this recently as well and are investigating.  Here is what we have learned so far.

- The error is being thrown from mineral's `createThemedComponent` function.  
- The `propTypes` part of the error message is a misnomer while the real issue is with the `undefined`.
- I believe that it may be a circular dependency issue. 
- The problem seems to arise when components are imported from the package index, as in `import { Button } from 'mineral-ui'`.

A workaround seems to be importing components from their individual paths, as in `import Button from mineral-ui/Button` or `import Checkbox, { CheckboxGroup } from 'mineral-ui/Checkbox'`.  If you have any questions about the import syntax for a particular component, you can find it at the top of each component page, e.g. https://mineral-ui.com/components/button#import-syntax

Please let me know if you are in fact importing components from the package index and if using the alternate import syntax works for you.

**Comment by oupvo01** [comment]
I've got to add that it works in local dev mode e.g. `npm start` but not in the production build e.g. `npm build`.

**Comment by brentertz** [comment]
Hi @oupvo01 I believe that this likely is a separate issue.

FormField's children, or input prop is expected to be one of the mineral-ui form input components.  If it is an HTML element you would see this issue.  If it is a custom component, then props will need to be routed appropriately.  I have created a CodeSandbox to replicate how I might envision the problem occurring, but it is only a guess.  https://codesandbox.io/s/1z4rx8yyq  

Further, it does not make sense to me that it would work in dev mode but not in production.  I can cause the issue either way, using an HTML element instead of a mineral-ui input component.

To investigate further, I would need to know more about how you are using the FormField component, ideally via a CodeSandbox.

**Comment by brentertz** [comment]
Hi @oupvo01 I believe that we have a fix for the aforementioned import syntax issue.  It should hopefully be merged and released today.  When that is merged, I am going to close this issue.

If you would like to continue to discuss the issue that you were having with the FormField component, I would ask that you please file a separate issue.  We are happy to continue to help.

**Comment by brentertz** [comment]
This fix has been release in `mineral-ui@0.49.0`
