### ISSUE TITLE
Text font-size uses px instead of em 

### ISSUE THREAD

**Issue by calummoore** [mineral-ui/mineral-ui#826]
### Expected behavior
```js
<Text as='h1'>Heading</Text>
```

Should result in font-size of `2.125em` instead it is `2.125px`

### Current behavior
Font size is set to `2.125px`

### Possible solution
If I remove `fontSize_base` it fixes the problem.

```js
const theme = createTheme({
  overrides: {
    fontSize_base: '1em', // <---- this appears to be the problem
    h1_fontWeight: '600',
    boxShadow_2: '0 2px 4px 0 rgba(187, 187, 187, 0.2)',
  },
})
```

### Steps to reproduce (for bugs)

<details><summary>theme.mineral.js</summary><p>

```js
import { createTheme } from 'mineral-ui/themes'

const theme = createTheme({
  overrides: {
    fontSize_base: '1em',
    h1_fontWeight: '600',
    boxShadow_2: '0 2px 4px 0 rgba(187, 187, 187, 0.2)',
  },
})

export default theme
```
</p></details>

### 

### Version
"mineral-ui": "^0.57.0",

### Environment
create-react-app

**Comment by kylegach** [comment]
Thanks for noticing this, @calummoore.

I'm looking into it, and will keep you posted. Have you noticed issues with any other components when setting a `fontSize_base` override?

**Comment by kylegach** [comment]
For a quick (temporary) workaround, you can define a `fontSize_base` override using `px` units, as demonstrated here: https://codesandbox.io/s/9z0m982wqr. It's not a long-term solution, because `fontSize` theme values should use `em` units as you attempted.

**Comment by calummoore** [comment]
Hi @kylegach, no problem. This is an awesome library! The first component library that's been a joy to use!

Thanks for the workaround! Does setting the `fontSize_base` to `16 * 2` result in a 1em equivalent?

Not yet - I'll post here if I find anything else related to sizing.

One other thing, I'm actually setting the `fontSize_base` to `1em` even though it says that is the default value. However, without setting that value none of the components respect my global fontSize of `14px`. So that was my goal with setting the `fontSize_base`.

**Comment by kylegach** [comment]
> This is an awesome library! The first component library that's been a joy to use!

Wow. Thank you for the kind words! 😊

> Does setting the fontSize_base to 16 * 2 result in a 1em equivalent?

No, just 16 is equal to 1em. I multiplied by 2 to demonstrate that it was taking effect. 

> One other thing, I'm actually setting the fontSize_base to 1em even though it says that is the default value. However, without setting that value none of the components respect my global fontSize of 14px. So that was my goal with setting the fontSize_base.

Mineral components are designed to be _completely_ independent and unaffected by the surrounding app styles. If you look at the root element of any component, you’ll see that a font-size, font-family, color, box-sizing, etc... (set via [`componentStyleReset`](https://github.com/mineral-ui/mineral-ui/blob/master/src/library/styles/componentStyleReset.js)) are applied to each, rather than relying on a more typical global style.

If you wish to make the components respect your global font-size of 14px, you can set an override of `fontSize_base: 14` (for now; after I get a fix in, it’ll be `'0.875em'`).

Although, this discussion is making me think that maybe `fontSize_base` _should_ be in `px`, to avoid some of this confusion. I.e., it’s totally logical that you’d set it to `'1em'`, as that _is_ 14px in your app. Using `px` would make that unambiguous. 🤔

**Comment by calummoore** [comment]
Yeah, because I believe in css that `em` is relative to it's parent fontSize, it only defaults to 16px because that's the default `fontSize` for a browser. 

I think if you're not respecting the parent / globally set `fontSize` (which I understand your reasons for),  then it should be px value, with the default set to 16px - and then everything is relative to that value.

**Comment by kylegach** [comment]
@calummoore — You convinced me. 😄 Just submitted a PR (#829) to update the docs to reflect the fact that `fontSize_base` is always used as `px` units throughout our styles, and thus any override should also use those units. It's always worked this way, functionally; the PR simply updates the docs to match. 🤦‍♂️

Therefore, what I said above about using `14` as a temporary workaround for your case is no longer temporary nor a workaround; it's the only way to do it. 😅 You also don't need to wait for that PR to be merged & released as it functions this way currently.

Thanks for your input on this issue, Cal. We appreciate it!
