### ISSUE TITLE
ℹ️ Status of Mineral UI

### ISSUE THREAD

**Issue by kylegach** [mineral-ui/mineral-ui#845]
All,

We have published a document regarding the status of this project: https://github.com/mineral-ui/mineral-ui/blob/master/docs/status-of-mineral-ui.md

Thank you for your support!

**Comment by gsklee** [comment]
Hey @kylegach, this is certainly a sad news... I really like the efforts Mineral UI put into your color palette selections (https://uxplanet.org/designing-systematic-colors-b5d2605b15c), and was / am still considering using it for a personal project.

Just wondering how much support do you envision the former core team is able to offer to new maintainers? Do you think creating / extending the design system's current component library is still something doable? Or do you think, in general, this design system will no longer get any substantial updates from its original conceivers / designers, and is basically in a maintenance mode even with volunteering community maintainers?

**Comment by kylegach** [comment]
Good questions, @gsklee.

I think extending the current component library is entirely doable, even without substantial updates from the original maintainers (which is pretty much a given, at this point). We (@brentertz and I, at least) will do whatever we can to help new maintainers get started, so that the project can continue and/or become whatever it needs to be.

**Comment by gsklee** [comment]
Thanks @kylegach. Are you or @brentertz also the design mastermind behind this design language? I guess my real question was, is there still someone from the original design team willing to keep working on improving, and offering design critiques for Mineral UI as an open-source project? Because if that unfortunately is not going to be the case, we risk creating disharmony between any new additions or modifications and the original designs. I might be more inclined to scrap Mineral UI's design tokens and apply them to some other pattern library under such a scenario.

**Comment by kylegach** [comment]
@gsklee — No, we didn't do much of the design. Those team members are no longer with the company and have not contributed to the project in quite some time. That said, we found that enough design work had been done to reliably extrapolate any missing pieces. So, if the future maintainers wish to keep the current look-and-feel, they'll likely be able to do so.

I want to note, though, that we will hand over the entire project, including its roadmap, to those future maintainers. So there's no guarantee the look-and-feel will not change, whether in a minor or major fashion.

**Comment by kylegach** [comment]
_We received some questions that would be helpful for others, so I'm re-sharing here, with permission._

#### What does taking over the project entail?
Whatever you would like it to. :) We would prefer to find maintainers that plan to continue accepting open source contributions, as that is in line with the spirit of the initial project.

#### If we took over the project, I'm assuming we'd have full control of the roadmap as well. Correct?
Yep! We still have some internal consumers of the tokens, so we need to figure out a proper migration for that bit. Once that's handled, you'll have free reign. As maintainers, we have some ideas of next steps we would have liked to take, and are happy to share those, if you'd like to hear them.

#### Can we take over the domain mineral-ui.com? Is the site still up? How/where is that hosted?
The site is hosted on Netlify, and it would normally be up, but we're having some kind of [certificate issue](https://github.com/mineral-ui/mineral-ui/issues/846). The domain was registered by the corporation, so getting that transferred would likely be tricky, but is something we'd like to make available.

#### Other than the website, are there any other costs involved in maintaining the project?
[Netlify](https://www.netlify.com/) offers a free "starter" plan for open source projects, so the only cost of the website is the domain registration. Our CI, [Travis](https://travis-ci.org/), is also free for open source projects. We use [Happo.io](https://happo.io/) for visual regression testing. That is currently free, through an arrangement with the founder of that service (basically, we helped him beta test with our project). We'd need to discuss with him if that arrangement could continue with new maintainers. I cannot think of any other services we use, particularly ones that cost anything. Aside from the design, development, and project management efforts involved, it was a purposefully inexpensive project.

**Comment by oliviertassinari** [comment]
@kylegach It's a sad new :'(. I have enjoyed benchmarking this framework when working on new features for Material-UI.

**Comment by gsklee** [comment]
Hey @kylegach, I've given it some thought, and finally decided to throw myself in. Apparently I won't be able to pump up the same level of activities for Mineral UI as you guys did, but part of my day job involves running DesignOps and building the DLS implementation for our organization, I feel like by helping out here I can benefit from your awesome work and also keeping it fresh as I make new discoveries and learn new things along the journey.

I think I won't introduce any drastic change into Mineral UI during the handover period; will just be focusing on issue triaging and bug PRs reviewing and merging while familiarizing myself with the codebase and waiting for your code migration to complete. After that we'll take a look at the prioritized backlog and get things moving again. First thing I'd like to do is to adopt the [System UI Theme Spec](https://system-ui.com/) for Mineral UI design tokens and the theme object to allow for better interoperability with other design system implementations. @oliviertassinari since you happen to be here, I know it's also something on [Material UI's roadmap](https://material-ui.com/discover-more/roadmap/) and would be great to see this happen on your end as well 🙂

@kylegach I'll shoot you an email shortly for follow-up discussions.

**Comment by oliviertassinari** [comment]
@gsklee We will see what we can do, from a Breaking Change perspective with Theme Spec, I also like Tailwind theme structure, but it's a bit different.

Haha, they are so many great UI frameworks to benchmark on, it's 🏅. 

![Capture d’écran 2019-11-16 à 00 36 37](https://user-images.githubusercontent.com/3165635/68982963-3ed38980-0809-11ea-8f54-eb4e65b60243.png)

**Comment by gsklee** [comment]
Hey @kylegach, just checking in and see if you are still keen to do this.

**Comment by kylegach** [comment]
Good news! The kind folks at TargetX have agreed to take over responsibilities for Mineral UI. The current maintainers, basically @brentertz and I, will remain in an advisory role. We're crafting a more official statement for the community, but wanted to at least share that Mineral does indeed have a future. @natorojr, anything to add?

@gsklee — We'll put you in touch with the TargetX team. You both have similar visions for future direction. :)

**Comment by tx-nestor** [comment]
Thanks for the introduction, @kylegach 

TargetX is happy to become the next corporate sponsors and stewards of Mineral UI. In early 2019, we made a fairly big investment in Mineral UI as our foundational UI Kit for many of our latest products. As such, we are committed to protecting our investment by volunteering to maintain the current version for as long as the community needs it. We also hope to kick-off and spearhead the development of the next major version of Mineral UI alongside our maintenance efforts.

After the transition is complete (realistically early 2020 with the holidays upon us), I'll post a separate message regarding our ideas on the Mineral UI roadmap (both short and long-term) and our thoughts on the direction of the project in general.

Until then, rest assured that TargetX, myself and the 4 engineers I have allocated to maintain this project, will do our best to keep Mineral UI alive and well maintained for the foreseeable future.

Thanks to @kylegach and @brentertz for all of the hard work put into conceiving and launching Mineral UI, to begin with. We're looking forward to having you on the advisory board.

Best to all.

**Comment by stephane-klein** [comment]
@gsklee do you have some news ? 🙂

**Comment by gsklee** [comment]
@stephane-klein In holiday mode right now but yeah, still keen to help. @kylegach let's catch up after mid-Jan!

**Comment by tx-nestor** [comment]
Greetings community,

I'd like to announce that TargetX has officially become Mineral UI's new stewards and maintainers. TargetX will provide corporate sponsorship to the project in the form of volunteering our own development staff's time to help keep the project alive.

As the new maintainers of Mineral UI, the TargetX team is committed to:
- addressing bugs in a timely manner
- keeping dependent packages reasonably up-to-date and vulnerability free
- making non-breaking incremental improvements to the existing component library
- keeping the website and documentation updated
- honoring the project's open-source philosophy
- welcoming community contributions

That said, the TargetX team does NOT intend to make any significant changes or refactoring of the existing code base, nor will we continue to add components to the library. Instead, we will eventually create a new code repository (project name T.B.D.) where we'll start developing Mineral UI's successor from the ground up using the latest React features, TypeScript, Storybook, and styled-system (but still heavily influenced by the existing project's core design principles).

Our immediate action items are as follows:
1. Fix the outdated flow type issues which are failing PR checks
2. Fix the mineral-ui.com site (currently down due to an SSL certificate issue)
3. Update npm package dependencies (some of which are reported to have vulnerabilities)
4. Address any outstanding bugs/defects <== Note: if you have filed bugs against Mineral UI and they have not yet been addressed, now would be a good time to bump those up.
5. Make some incremental non-breaking enhancements to the existing components' props interface

I'm going to close this issue on account that the project now has new maintainers. That said if you have other suggestions/comments regarding the direction of the project, please feel free to start a separate thread.

Thanks,
VP of Product Engineering @ TargetX
